### ISSUE TITLE
Example tab is missing in pub.dev

### ISSUE THREAD

**Issue by guyluz11** [nathanielgreen/lifx_http_api#2]
An `Example` tab is missing in the [pub.dev](https://pub.dev/packages/lifx_http_api) page of this package.

![image](https://user-images.githubusercontent.com/9304740/135615153-1ed66726-5afc-4df2-a815-ae618ec1250d.png)

Example to one with `Example` tab

![image](https://user-images.githubusercontent.com/9304740/135615355-3471c2c5-6f84-44e1-b790-4eff326cc990.png)

**Comment by nathanielgreen** [comment]
Ah good catch thanks, I've added an example in the latest release as part of commit c35072223cbaa5bdc0dae92b9f58e9368fc4636f

Happy to alter if anything is unclear, otherwise I'll close this issue in a few days

**Comment by guyluz11** [comment]
Sounds good
Thanks

**Comment by guyluz11** [comment]
`Example` tab has been added.
Will close this issue now.
