### ISSUE TITLE
LIFX API key link is missing in the instructions

### ISSUE THREAD

**Issue by guyluz11** [nathanielgreen/lifx_http_api#3]
Link to create the [LIFX API key](https://cloud.lifx.com/) needs to be added to the instructions/readme file.

From the main site [https://www.lifx.com](https://www.lifx.com/) and from the [LIFX HTTP API](https://api.developer.lifx.com/docs/introduction) site you can't generate the api key as far as I saw.

**Comment by nathanielgreen** [comment]
Added link to README in e45787b8b3fb47ec670b282dc1977a2cd04de46e
