### ISSUE TITLE
json_serializable version can be updated

### ISSUE THREAD

**Issue by guyluz11** [nathanielgreen/lifx_http_api#4]
The project currently uses `json_serializable` packages version `^4.1.3` where the last version is `5.0.2`

![image](https://user-images.githubusercontent.com/9304740/135671414-bc6d5c45-f452-483e-b456-6b719296ff11.png)

We get fewer points in pub.dev for that.

In my project it conflicts 

Pub get: 

``` 
Resolving dependencies...
Because lifx_http_api >=0.0.3 depends on json_serializable ^4.1.3 and cbj_hub depends on json_serializable ^5.0.0, lifx_http_api >=0.0.3 is forbidden.
So, because cbj_hub depends on lifx_http_api ^0.0.11+2, version solving failed.
```

**Comment by nathanielgreen** [comment]
Fixed as of #5
