### ISSUE TITLE
json_serializable is out of date

### ISSUE THREAD

**Issue by guyluz11** [nathanielgreen/lifx_http_api#6]
I am getting errors for low `json_serializable` version from here

```
Because lifx_http_api >=0.0.11+3 depends on json_serializable ^5.0.0 and cbj_hub depends on json_serializable ^6.0.1, lifx_http_api >=0.0.11+3 is forbidden.
So, because cbj_hub depends on lifx_http_api ^0.0.12, version solving failed.
```

![image](https://user-images.githubusercontent.com/9304740/140527860-716a97c3-3705-45ff-bb05-277e762116f2.png)

Can we please update the `json_serializable` version to `6.0.1`?

**Comment by nathanielgreen** [comment]
Sure thing, I've made the updates in 0.0.13, and just published it to pub.dev, so should be available soon
