### ISSUE TITLE
Update lint package version

### ISSUE THREAD

**Issue by guyluz11** [nathanielgreen/lifx_http_api#7]
It seems that our current lint version is old, updating it should not impact the functionality.

```dart
Because lifx_http_api 0.0.13 depends on lint ^1.5.3 and no versions of lifx_http_api match >0.0.13 <0.1.0, lifx_http_api ^0.0.13 requires lint ^1.5.3.
So, because cbj_hub depends on both lifx_http_api ^0.0.13 and lint ^2.0.1, version solving failed.
```

**Comment by nathanielgreen** [comment]
Will update that later today 👍

**Comment by guyluz11** [comment]
I tried to update it but it looks like the project isn't compiling on the master branch.
Getting errors `Target of URI doesn't exist: 'package:lifx_http_api/src/responses/responses.dart'`.

Are you usually working on one of the other branches ?, or should I add `lifx_http_api` package to the outer pubspac.yaml (not the one in the packages directory)

**Comment by nathanielgreen** [comment]
Hey sorry about the wait, I've just updated the package with version 0.0.14 which should be live on pub.dev soon. Check the CHANGELOG.md for the breaking changes.

**Comment by guyluz11** [comment]
😁 Thanks

I guess I can close this issue now.
